"use client";
import {useState,useRef,useEffect} from "react";
import {cloudToken} from "@/lib/cloud";
import type {Job} from "@/lib/data";
export default function AiCapture({message,onDraft,compact=false}:{message:string;onDraft:(j:Job)=>void;compact?:boolean}){
 const [enabled,setEnabled]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[recording,setRecording]=useState(false);
 const recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null),alive=useRef(true);
 useEffect(()=>{alive.current=true;fetch("/api/extract").then(r=>r.json()).then(d=>setEnabled(d.enabled)).catch(()=>{});return()=>{alive.current=false;if(timer.current)clearTimeout(timer.current);if(recorder.current&&recorder.current.state!=="inactive")recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop())}},[]);
 async function extract(file?:File){setBusy(true);setError("");try{const token=await cloudToken();const form=new FormData();form.set("text",message);form.set("today",new Date().toLocaleDateString("en-CA"));if(file)form.set("file",file);const r=await fetch("/api/extract",{method:"POST",headers:{Authorization:`Bearer ${token}`},body:form});const result=await r.json();if(!r.ok)throw new Error(result.error||"Capture failed.");const d=result.draft;onDraft({id:"",customer:String(d.customer||"").slice(0,100),work:String(d.work||"").slice(0,500),total:Math.max(0,Number(d.total)||0),paid:Math.max(0,Number(d.paid)||0),date:/^\d{4}-\d{2}-\d{2}$/.test(d.date)?d.date:"",time:/^\d{2}:\d{2}$/.test(d.time)?d.time:"",status:"Waiting",source:String(d.source||message).slice(0,12000)});}catch(e){setError(e instanceof Error?e.message:"Please try again.")}finally{setBusy(false)}}
 async function record(){if(recording){recorder.current?.stop();return}try{await cloudToken();if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw new Error("Recording is unavailable in this browser. Upload a voice note instead.");stream.current=await navigator.mediaDevices.getUserMedia({audio:true});const m=new MediaRecorder(stream.current);recorder.current=m;const chunks:Blob[]=[];m.ondataavailable=e=>chunks.push(e.data);m.onstop=()=>{if(timer.current)clearTimeout(timer.current);stream.current?.getTracks().forEach(t=>t.stop());if(!alive.current)return;setRecording(false);const mime=m.mimeType.split(";")[0];const blob=new File(chunks,`recording.${mime.includes("mp4")?"m4a":"webm"}`,{type:mime});void extract(blob)};m.start();setRecording(true);timer.current=setTimeout(()=>{if(m.state!=="inactive")m.stop()},60000);}catch(e){stream.current?.getTracks().forEach(t=>t.stop());setError(e instanceof Error?e.message:"Microphone unavailable.")}}
 return compact?<div className="compact-capture"><label className="chat-attach" aria-label="Attach screenshot or voice note" title={enabled?"Attach screenshot or voice note":"AI attachments unlock after setup"}><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m21.4 11.6-8.9 8.9a6 6 0 0 1-8.5-8.5l9.2-9.2a4 4 0 0 1 5.7 5.7l-9.2 9.2a2 2 0 1 1-2.8-2.8l8.5-8.5"/></svg><input type="file" disabled={!enabled||busy||recording} accept="image/png,image/jpeg,image/webp,audio/mpeg,audio/mp4,audio/wav,audio/webm" onChange={e=>{const f=e.target.files?.[0];if(f)void extract(f);e.target.value=""}}/></label><button type="button" className={recording?"chat-mic recording":"chat-mic"} aria-label={recording?"Stop recording":"Record voice note"} title={enabled?"Record a voice note":"Voice notes unlock after AI setup"} disabled={busy} onClick={record}><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 14a3 3 0 0 0 3-3V6a3 3 0 0 0-6 0v5a3 3 0 0 0 3 3Z M5 11a7 7 0 0 0 14 0 M12 18v3 M9 21h6"/></svg></button>{error&&<span className="compact-error" role="alert">{error}</span>}</div>:<div className="ai-capture"><div className="capture-tools"><button className="outline" disabled={!enabled||busy||!message.trim()||recording} onClick={()=>extract()}>{busy?"Reading details…":"Read with AI"}</button><label className={!enabled||busy||recording?"upload disabled":"upload"}>Screenshot / voice note<input type="file" disabled={!enabled||busy||recording} accept="image/png,image/jpeg,image/webp,audio/mpeg,audio/mp4,audio/wav,audio/webm" onChange={e=>{const f=e.target.files?.[0];if(f)void extract(f);e.target.value=""}}/></label><button className="outline" disabled={!enabled||busy} onClick={record}>{recording?"Stop recording":"Record voice"}</button></div><small>{enabled?"AI capture uses your signed-in account. Review all details before saving.":"AI, screenshot and voice capture will unlock when the creator connects the AI service."}</small>{error&&<p role="alert">{error}</p>}</div>
}
