"use client";
import { useEffect, useState } from "react";
import {cloudConfigured,sendCode,verifyCode,saveCloud,loadCloud,signOut,signedIn} from "@/lib/cloud";
import {isSnapshot,type Snapshot} from "@/lib/data";

export default function CloudSettings({snapshot,onRestore}:{snapshot:Snapshot;onRestore:(s:Snapshot)=>void}){
 const [phone,setPhone]=useState("+91"),[code,setCode]=useState(""),[sent,setSent]=useState(false),[logged,setLogged]=useState(signedIn),[busy,setBusy]=useState(false),[status,setStatus]=useState(""),[dark,setDark]=useState(false);
 // Read the device preference after hydration.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{const isDark=localStorage.getItem("pakki-baat-theme")==="dark";setDark(isDark);document.documentElement.dataset.theme=isDark?"dark":"light"},[]);
 function toggleTheme(){const next=!dark;setDark(next);localStorage.setItem("pakki-baat-theme",next?"dark":"light");document.documentElement.dataset.theme=next?"dark":"light"}
 async function action(fn:()=>Promise<void>){setBusy(true);setStatus("");try{await fn()}catch(e){setStatus(e instanceof Error?e.message:"Please try again.")}finally{setBusy(false)}}
 return <div className="cloud-settings"><div className="theme-control"><div><strong>Appearance</strong><small>Choose the look that feels comfortable.</small></div><button type="button" className={dark?"switch on":"switch"} role="switch" aria-checked={dark} aria-label="Toggle dark mode" onClick={toggleTheme}><span/></button></div><h3>Keep your business with you</h3><p>Phone sign-in and a cloud backup. No email needed.</p>{!cloudConfigured?<div className="notice">Cloud setup is not connected yet. Local trial features work now.</div>:!logged?<><label>Phone number<input type="tel" value={phone} onChange={e=>setPhone(e.target.value)} autoComplete="tel"/></label><button className="outline" disabled={busy} onClick={()=>action(async()=>{await sendCode(phone);setSent(true);setStatus("Code sent by SMS.")})}>{sent?"Resend code":"Send sign-in code"}</button>{sent&&<><label>SMS code<input inputMode="numeric" autoComplete="one-time-code" value={code} onChange={e=>setCode(e.target.value)} maxLength={8}/></label><button className="primary" disabled={busy||!code} onClick={()=>action(async()=>{await verifyCode(phone,code);setLogged(true);setStatus("Signed in. Save a backup or restore your cloud workspace.")})}>Verify code</button></>}</>:<div className="cloud-buttons"><button className="primary" disabled={busy} onClick={()=>action(async()=>{if(!confirm("Replace your cloud backup with this device’s workspace? Export a local backup first if needed."))return;await saveCloud(snapshot);setStatus("Cloud backup saved.")})}>Save cloud backup</button><button className="outline" disabled={busy} onClick={()=>action(async()=>{const s=await loadCloud();if(!s){setStatus("No cloud backup yet.");return}if(!isSnapshot(s))throw new Error("The cloud backup is not a valid workspace.");if(confirm("Restore cloud backup? This replaces this device’s current workspace.")){onRestore(s);setStatus("Cloud backup restored.")}})}>Restore cloud backup</button><button className="text-button" onClick={()=>{signOut();setLogged(false);setStatus("Signed out. Local data is still on this device.")}}>Sign out</button></div>}{status&&<p role="status">{status}</p>}<small>Backups are manual. Sign in again after refreshing for cloud access.</small></div>
}
