"use client";
import { useEffect, useState } from "react";
import "./workspace.css";
import "./connections.css";
import CloudSettings from "./cloud-settings";
import AiCapture from "./ai-capture";
import {isSnapshot,calendarFile,type Job,type Snapshot} from "@/lib/data";
type Tab = "Today" | "My assistant" | "Commitments" | "Customers" | "Settings";
const blank = ():Job => ({id:"",customer:"",work:"",total:0,paid:0,date:"",time:"",status:"Waiting",source:""});
const money=(n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(n);
const day=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;};
function Icon({name,size=22}:{name:string;size?:number}){const p:Record<string,string>={home:"m3 10 9-7 9 7v10H3Z M9 20v-7h6v7",chat:"M21 11a9 9 0 0 1-9 9H4l-2 2V11a9 9 0 1 1 19 0Z M7 9h9 M7 13h6",list:"M8 5h13 M8 12h13 M8 19h13 M3 5h.01 M3 12h.01 M3 19h.01",people:"M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2 M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8 M17 4a4 4 0 0 1 0 7 M22 21v-2a4 4 0 0 0-3-4",settings:"M12 3v3 M12 18v3 M3 12h3 M18 12h3 M5 5l3 3 M16 16l3 3 M5 19l3-3 M16 8l3-3 M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0",plus:"M12 5v14 M5 12h14",arrow:"M5 12h14 m-6-6 6 6-6 6",check:"m5 12 4 4L19 6",bell:"M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9 M10 21h4",clock:"M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0 M12 7v5l3 2",copy:"M9 9h12v12H9Z M5 15H3V3h12v2",search:"M17 10a7 7 0 1 1-14 0 7 7 0 0 1 14 0 m-2 5 6 6",close:"m6 6 12 12 M6 18 18 6",leaf:"M5 20c0-10 6-15 15-16 0 10-5 16-15 16Z M5 20l10-10"};return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={p[name]||p.chat}/></svg>}
export default function Workspace(){
 const [tab,setTab]=useState<Tab>("Today"),[jobs,setJobs]=useState<Job[]>([]),[ready,setReady]=useState(false),[owner,setOwner]=useState("Asha"),[business,setBusiness]=useState("My small business"),[message,setMessage]=useState(""),[draft,setDraft]=useState<Job|null>(null),[reply,setReply]=useState<Job|null>(null),[query,setQuery]=useState(""),[filter,setFilter]=useState("All"),[toast,setToast]=useState(""),[feedback,setFeedback]=useState("");
 // Hydrate the device workspace after SSR; browser storage is unavailable on the server.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{try{const s=JSON.parse(localStorage.getItem("pakki-baat-v1")||"null");if(s!==null){if(!isSnapshot(s))throw new Error("Invalid backup");setJobs(s.jobs);setOwner(s.owner);setBusiness(s.business)}}catch{setToast("Saved data could not be read. Restore a valid backup in Settings.");return}setReady(true)},[]);
 // Report a browser-storage write failure so users can export their unsaved changes.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{if(ready)try{localStorage.setItem("pakki-baat-v1",JSON.stringify({jobs,owner,business}))}catch{setToast("Storage is full. Export a backup before closing.")}},[jobs,owner,business,ready]);
 useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(""),4500);return()=>clearTimeout(id)},[toast]);
 const modalOpen=Boolean(draft||reply);
 useEffect(()=>{if(!modalOpen)return;const previous=document.activeElement as HTMLElement|null;const handler=(e:KeyboardEvent)=>{if(e.key==="Escape"){setDraft(null);setReply(null)}if(e.key==="Tab"){const nodes=document.querySelectorAll<HTMLElement>('[role="dialog"] button:not(:disabled), [role="dialog"] input, [role="dialog"] textarea, [role="dialog"] select, [role="dialog"] summary');const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&(document.activeElement===first||!document.querySelector('[role="dialog"]')?.contains(document.activeElement))){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener("keydown",handler);return()=>{document.removeEventListener("keydown",handler);previous?.focus()}},[modalOpen]);
 const nav:[Tab,string][]=[["Today","home"],["My assistant","chat"],["Commitments","list"],["Customers","people"]];
 const open=jobs.filter(j=>j.status!=="Completed"),due=open.filter(j=>j.date&&j.date<=day()),balance=jobs.reduce((a,j)=>a+Math.max(0,j.total-j.paid),0);
 const visible=jobs.filter(j=>`${j.customer} ${j.work}`.toLowerCase().includes(query.toLowerCase())&&(filter==="All"||(filter==="Payment due"?j.total>j.paid:filter==="Due now"?j.status!=="Completed"&&Boolean(j.date)&&j.date<=day():j.status===filter)));
 function go(t:Tab){setTab(t);setQuery("");setFilter("All")}
 function capture(){if(!message.trim())return;const m=message.match(/total(?:\s+is)?\s*[:=-]?\s*(?:₹|rs\.?|inr)?\s*([\d,]+(?:\.\d{1,2})?)/i);setDraft({...blank(),work:message.trim().slice(0,150),source:message.trim(),total:m?Number(m[1].replaceAll(",","")):0})}
 function save(){if(!draft||!draft.customer.trim()||!draft.work.trim())return;if(!Number.isFinite(draft.total)||!Number.isFinite(draft.paid)||draft.total<0||draft.paid<0||draft.paid>draft.total){setToast("Check the total and received amounts.");return}const item={...draft,id:draft.id||crypto.randomUUID(),customer:draft.customer.trim(),work:draft.work.trim()};setJobs(p=>[item,...p.filter(j=>j.id!==item.id)]);setDraft(null);setReply(item);setMessage("");setToast("Saved. Your next steps are ready.")}
 const replyText=(j:Job)=>`Hi ${j.customer}, here are the details for ${j.work}. ${j.date?`Date: ${j.date}${j.time?` at ${j.time}`:" (time to be agreed)"}. `:"Please confirm a date. "}Total: ${money(j.total)}. Received: ${money(j.paid)}. Balance: ${money(j.total-j.paid)}. Please reply to confirm these details. Thank you!`;
 async function shareFeedback(){try{if(navigator.share){await navigator.share({title:"Pakki Baat feedback",text:feedback})}else{await navigator.clipboard.writeText(feedback);setToast("Feedback copied. Paste it into your chat with the creator.")}}catch(e){if(e instanceof Error&&e.name==="AbortError")return;setToast("Sharing is unavailable. Download your feedback instead.")}}
 async function copy(t:string){try{await navigator.clipboard.writeText(t);setToast("Copied. Paste it into your customer's chat.")}catch{setToast("Please select and copy the message manually.")}}
 function download(text:string,name:string){const u=URL.createObjectURL(new Blob([text],{type:"text/plain"})),a=document.createElement("a");a.href=u;a.download=name;a.click();URL.revokeObjectURL(u)}
 function sample(){setJobs([{...blank(),id:crypto.randomUUID(),customer:"Riya Shah",work:"2 kg chocolate cake",total:2400,paid:1000,date:day(),time:"17:00",status:"Confirmed",source:"Sample commitment"},{...blank(),id:crypto.randomUUID(),customer:"Meera Patel",work:"Blouse alterations & fitting",total:1200,paid:0,date:day(),source:"Sample commitment"}]);setToast("Sample commitments added. Edit or delete them freely.")}
 function restore(s:Snapshot){setJobs(s.jobs);setOwner(s.owner);setBusiness(s.business);setReady(true);setToast("Workspace restored on this device.")}
 async function importBackup(file:File){try{if(file.size>10_000_000)throw new Error("Backup is too large.");const data=JSON.parse(await file.text());if(!isSnapshot(data))throw new Error("This is not a valid Pakki Baat backup.");if(confirm("Replace this device’s workspace with this backup?"))restore(data)}catch(e){setToast(e instanceof Error?e.message:"Could not read this backup.")}}
 const jobCard=(j:Job)=><button className="job" key={j.id} onClick={()=>setDraft(j)}><span className="avatar">{j.customer[0]}</span><span className="job-main"><strong>{j.customer}</strong><span>{j.work}</span><small>{j.date?new Date(j.date+"T12:00:00").toLocaleDateString("en-IN",{day:"numeric",month:"short"}):"Date to be agreed"}{j.time?" · "+j.time:""}</small></span><span className="job-end"><strong>{money(j.total-j.paid)}</strong><span className={j.status==="Confirmed"?"tag green":"tag"}>{j.status}</span></span><Icon name="arrow" size={16}/></button>;
 return <div className="shell"><aside className="sidebar"><button className="brand" onClick={()=>go("Today")}><Icon name="leaf" size={29}/>pakki baat<span>.</span></button><div className="workspace"><span className="avatar coral">{owner[0]}</span><div><strong>{business}</strong><small>Your little workspace</small></div></div><span className="eyebrow nav-label">YOUR WORKSPACE</span><nav>{nav.map(([t,i])=><button key={t} className={tab===t?"active":""} onClick={()=>go(t)}><Icon name={i}/>{t}{t==="Today"&&due.length>0&&<b>{due.length}</b>}</button>)}</nav><div className="sidebar-bottom"><div className="help-card"><span>Small business. Big heart.</span><p>A little less remembering.<br/>A little more doing what you love.</p><Icon name="leaf" size={32}/></div><button className="settings-button" onClick={()=>go("Settings")}><Icon name="settings"/>Settings & feedback</button><div className="account"><span className="avatar">{owner[0]}</span><div><strong>{owner}</strong><small>Local trial workspace</small></div></div></div></aside>
 <main><header className="topbar"><div className="breadcrumb">Your workspace <span>/</span><strong>{tab}</strong></div><div className="top-actions"><span className="saved-dot"/>{ready?"Device workspace":"Storage unavailable"}<button className="icon-button" aria-label="View reminders" onClick={()=>go("Today")}><Icon name="bell"/></button><span className="avatar small">{owner[0]}</span></div></header><div className="content">
 {tab==="Today"&&<><div className="page-heading"><div><div className="eyebrow">A LITTLE CLARITY FOR YOUR DAY</div><h1>Hello, {owner} <span className="sun">☀</span></h1><p>Let’s make room for the work you love.</p></div><button className="primary" onClick={()=>go("My assistant")}><Icon name="plus" size={18}/>Add customer message</button></div><section className="hero"><div className="hero-copy"><span className="pill">YOUR BUSINESS, A LITTLE LIGHTER</span><h2>Every little detail.<br/>Taken care of.</h2><p>A customer message, a voice note, a promise.<br/>Let’s turn it into your next clear step.</p><button className="dark-button" onClick={()=>go("My assistant")}>Tell me what’s new <Icon name="arrow" size={18}/></button></div><div className="hero-art" aria-hidden="true"><div className="art-circle"/><div className="note back"><span>Made with love</span><div className="cake">♨</div><span>And a little less worry.</span></div><div className="note front"><div className="note-icon"><Icon name="check"/></div><strong>It’s a pakki baat!</strong><span>Details saved. Mind at ease.</span><div className="note-line"/><div className="note-line short"/></div><span className="spark one">✦</span><span className="spark two">✧</span><span className="art-leaf"><Icon name="leaf" size={70}/></span></div></section>
 <section className="stats"><button onClick={()=>{go("Commitments");setFilter("Payment due")}}><span className="stat-icon peach">₹</span><div><span>Payments to collect</span><strong>{money(balance)}</strong><small>A gentle nudge goes a long way</small></div><Icon name="arrow" size={18}/></button><button onClick={()=>{go("Commitments");setFilter("Due now")}}><span className="stat-icon mint"><Icon name="clock"/></span><div><span>Due today or earlier</span><strong>{due.length} <em>commitments</em></strong><small>Keep your promises on time</small></div><Icon name="arrow" size={18}/></button><button onClick={()=>{go("Commitments");setFilter("Waiting")}}><span className="stat-icon yellow"><Icon name="chat"/></span><div><span>Waiting for a reply</span><strong>{open.filter(j=>j.status==="Waiting").length} <em>customers</em></strong><small>Pick up where you left off</small></div><Icon name="arrow" size={18}/></button></section>
 <div className="lower-grid"><section className="panel"><div className="section-heading"><h2>Needs a little attention <span className="count">{open.length}</span></h2><button className="text-button" onClick={()=>go("Commitments")}>View all <Icon name="arrow" size={15}/></button></div>{open.length?open.slice(0,4).map(jobCard):<div className="empty"><span className="empty-icon"><Icon name="check" size={28}/></span><h3>A fresh start, just for you</h3><p>Add your first customer message.<br/>We’ll help you keep the details together.</p>{!jobs.length&&<button className="text-button" onClick={sample}>Explore with sample commitments →</button>}</div>}</section><section className="tip-panel"><span className="eyebrow">YOUR POCKET ASSISTANT</span><h2>“Wait, what did<br/>she ask for?”</h2><p>Sound familiar? Paste a customer’s message and keep the work, amount and date in one place.</p><button className="outline" onClick={()=>go("My assistant")}>Let’s try it <Icon name="arrow" size={16}/></button><span className="tiny">Made for your everyday kind of busy.</span></section></div><footer>Made for small businesses with big dreams. <span>♡</span></footer></>}
 {tab==="My assistant"&&<><div className="page-heading"><div><div className="eyebrow">A HELPING HAND, ALWAYS</div><h1>Your pocket assistant</h1><p>Start with what your customer said.</p></div></div><section className="chat-layout"><div className="chat-panel"><div className="chat-header"><Icon name="leaf"/><div><strong>Pakki Baat</strong><small>Let’s get the details together</small></div></div><div className="chat-body"><span className="chat-date">A new conversation</span><div className="bubble"><strong>Hi {owner}! What’s the plan? 👋</strong><p>Paste a customer message, or tell me about the work. We’ll review the details together before saving.</p></div><button className="example" onClick={()=>setMessage("Riya wants a 2 kg chocolate cake. Total ₹2400. ₹1000 advance. Delivery on Saturday at 5 pm.")}>Try an example<span>“Riya wants a 2 kg chocolate cake…”</span></button><div className="local-note">Quick capture works without AI. Add the customer, dates and payment details in the next step.</div></div><div className="composer"><div className="chat-compose-row"><AiCapture compact message={message} onDraft={setDraft}/><textarea aria-label="Customer message" placeholder="Paste a message or tell me what’s needed…" value={message} onChange={e=>setMessage(e.target.value)} maxLength={6000}/><button type="button" className="chat-send" aria-label="Check details" title="Check details" onClick={capture} disabled={!message.trim()}><Icon name="arrow" size={19}/></button></div><div className="composer-actions"><span>{message.length}/6000 · Review before saving</span><button className="primary" onClick={capture} disabled={!message.trim()}>Check details <Icon name="arrow" size={18}/></button></div><div className="ai-note">Voice notes and attachments need AI setup; manual text capture works now.</div></div></div><aside className="capture-help"><h3>One message. A clear next step.</h3>{[["1","Tell us the details","Paste your customer’s message or write a short note."],["2","Check it together","Review the price, payment and date. You stay in control."],["3","Send a clear reply","Copy your confirmation and send it in your usual chat."]].map(([n,t,d])=><div key={n}><b>{n}</b><section><strong>{t}</strong><p>{d}</p></section></div>)}<p className="privacy-note">Screenshot and voice-note understanding need an AI service connection. Your pasted text is kept with each commitment.</p></aside></section></>}
 {tab==="Commitments"&&<><div className="page-heading"><div><div className="eyebrow">ALL YOUR PROMISES, TOGETHER</div><h1>Commitments</h1><p>Know what’s agreed, what’s due and what’s done.</p></div><button className="primary" onClick={()=>setDraft(blank())}><Icon name="plus"/>New commitment</button></div><div className="toolbar"><label className="search"><Icon name="search" size={19}/><input aria-label="Search commitments" placeholder="Search customer or work…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Filter commitments" value={filter} onChange={e=>setFilter(e.target.value)}>{["All","Waiting","Confirmed","Completed","Payment due","Due now"].map(x=><option key={x}>{x}</option>)}</select></div><section className="panel">{visible.length?visible.map(jobCard):<div className="empty"><Icon name="list" size={36}/><h3>No commitments here yet</h3><p>Add a message or create a commitment to get started.</p></div>}</section></>}
 {tab==="Customers"&&<><div className="page-heading"><div><div className="eyebrow">THE PEOPLE BEHIND YOUR BUSINESS</div><h1>Your customers</h1><p>Every conversation, a little easier to remember.</p></div></div><label className="search"><Icon name="search"/><input aria-label="Search customers" placeholder="Find a customer…" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="customer-grid">{Array.from(new Set(jobs.map(j=>j.customer))).filter(c=>c.toLowerCase().includes(query.toLowerCase())).map(c=>{const cj=jobs.filter(j=>j.customer===c);return <button className="customer-card" key={c} onClick={()=>{go("Commitments");setQuery(c)}}><span className="avatar large">{c[0]}</span><h3>{c}</h3><p>{cj.length} commitments</p><strong>{money(cj.reduce((a,j)=>a+j.total-j.paid,0))} to collect</strong><span>View history →</span></button>})}</div>{!jobs.length&&<div className="empty"><h3>Your customers will appear here</h3><p>Create a commitment to add your first customer.</p></div>}</>}
 {tab==="Settings"&&<><div className="page-heading"><div><div className="eyebrow">MAKE YOURSELF AT HOME</div><h1>Your workspace</h1><p>A few details to make Pakki Baat yours.</p></div></div><section className="settings-panel panel"><label>Your name<input value={owner} maxLength={60} onChange={e=>setOwner(e.target.value)}/></label><label>Business name<input value={business} maxLength={100} onChange={e=>setBusiness(e.target.value)}/></label><div className="notice"><strong>Local trial mode</strong><p>Your data is saved in this browser. Export a backup before clearing browser data or switching devices. Use a cloud backup after phone sign-in to move between devices.</p></div><button className="outline" onClick={()=>download(JSON.stringify({jobs,owner,business},null,2),"pakki-baat-backup.json")}>Export my data</button><label className="upload">Restore from a backup<input type="file" accept=".json,application/json" onChange={e=>{const f=e.target.files?.[0];if(f)void importBackup(f);e.target.value=""}}/></label><CloudSettings snapshot={{jobs,owner,business}} onRestore={restore}/><label>Tell us what could be better<textarea value={feedback} onChange={e=>setFeedback(e.target.value)} placeholder="What felt easy? What got in your way?"/></label><button className="outline" disabled={!feedback.trim()} onClick={shareFeedback}>Share feedback</button><button className="primary" disabled={!feedback.trim()} onClick={()=>{download(feedback,"pakki-baat-feedback.txt");setFeedback("");setToast("Feedback downloaded. Send this file to the creator.")}}>Download feedback</button></section></>}
 </div></main><nav className="mobile-nav">{nav.map(([t,i])=><button aria-label={t} key={t} className={tab===t?"active":""} onClick={()=>go(t)}><Icon name={i} size={21}/><span>{t==="My assistant"?"Assistant":t}</span></button>)}<button onClick={()=>go("Settings")}><Icon name="settings" size={21}/><span>Settings</span></button></nav>
 {draft&&<div className="modal-backdrop" onClick={()=>setDraft(null)}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="review-title" onClick={e=>e.stopPropagation()}><div className="section-heading"><div><span className="eyebrow">YOU’RE IN CONTROL</span><h2 id="review-title">Check the details</h2></div><button className="icon-button" aria-label="Close review" onClick={()=>setDraft(null)}><Icon name="close"/></button></div><p>Fill in anything missing. Nothing is sent automatically.</p><form onSubmit={e=>{e.preventDefault();save()}}><div className="form-grid"><label className="full">Customer name *<input autoFocus required maxLength={100} value={draft.customer} onChange={e=>setDraft({...draft,customer:e.target.value})}/></label><label className="full">What’s the work? *<textarea required maxLength={500} value={draft.work} onChange={e=>setDraft({...draft,work:e.target.value})}/></label><label>Total amount (₹)<input type="number" min="0" max="100000000" step="0.01" value={draft.total} onChange={e=>setDraft({...draft,total:Number(e.target.value)})}/></label><label>Amount received (₹)<input type="number" min="0" max={draft.total} step="0.01" value={draft.paid} onChange={e=>setDraft({...draft,paid:Number(e.target.value)})}/></label><label>Due date<input type="date" value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></label><label>Due time<input type="time" value={draft.time} onChange={e=>setDraft({...draft,time:e.target.value})}/></label><label className="full">Customer confirmation<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}>{["Waiting","Confirmed","Completed"].map(s=><option key={s}>{s}</option>)}</select></label></div>{(!draft.date||!draft.time)&&<div className="warning">Date or time still missing. Ask your customer before promising a deadline.</div>}{draft.source&&<details><summary>Original message</summary><p>{draft.source}</p></details>}<div className="modal-actions">{draft.id&&<button type="button" className="text-button danger" onClick={()=>{if(confirm("Delete this commitment? This cannot be undone.")){setJobs(jobs.filter(j=>j.id!==draft.id));setDraft(null)}}}>Delete</button>}<button className="primary" type="submit">Save & prepare reply <Icon name="check" size={18}/></button></div></form></section></div>}
 {reply&&<div className="modal-backdrop" onClick={()=>setReply(null)}><section className="modal reply-modal" role="dialog" aria-modal="true" aria-labelledby="reply-title" onClick={e=>e.stopPropagation()}><div className="section-heading"><h2 id="reply-title">A little clarity, ready to send</h2><button className="icon-button" aria-label="Close reply" onClick={()=>setReply(null)}><Icon name="close"/></button></div><p>Your commitment is saved. Send this yourself when ready.</p><div className="reply-bubble">{replyText(reply)}</div><button autoFocus className="primary" onClick={()=>copy(replyText(reply))}><Icon name="copy" size={18}/>Copy reply</button><button className="text-button" onClick={()=>{setDraft(reply);setReply(null)}}>Edit the details</button>{reply.date&&<button className="outline" onClick={()=>download(calendarFile(reply),"pakki-baat-reminder.ics")}>Add calendar reminder</button>}</section></div>}{toast&&<div className="toast" role="status">{toast}</div>}</div>
}
